[package]
name = "tryevdev"
version = "0.1.0"
authors = ["paul"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = "0.4.0"
