[package]
name = "fmachine"
version = "0.1.0"
authors = ["paul"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
libc = "0.2.81"
rppal = "0.11.3"
simple-signal = "1.1.1"
structopt = "0.3.21"

[dependencies.evdev-rs]
path = "../evdev-rs"

[dependencies.tokio]
version = "0.3.6"
features = ["full"]
